/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

export const Palette = {
  bg: '#FFF8F0',
  coral: '#FF6B5B',
  coralLight: '#FFE8E5',
  teal: '#3BBFAD',
  tealLight: '#DFF5F2',
  yellow: '#FFB830',
  yellowLight: '#FFF3D6',
  purple: '#9B7FE8',
  purpleLight: '#EEE8FB',
  green: '#4CC97A',
  greenLight: '#E0F8EB',
  card: '#FFFFFF',
  white: '#FFFFFF',
  black: '#000000',
  textDark: '#1A1A2E',
  textMid: '#555577',
  textSoft: '#AAAACC',
  blob1: '#FFE0D8',
  blob2: '#D8F0EE',
  blob3: '#FFF0CC',
  border: '#E8E2DB',
  danger: '#D64545',
  warningBg: '#FFF3D6',
  warningText: '#8A5A00',
  whiteAlpha10: 'rgba(255,255,255,0.1)',
  whiteAlpha12: 'rgba(255,255,255,0.12)',
  whiteAlpha22: 'rgba(255,255,255,0.22)',
  whiteAlpha70: 'rgba(255,255,255,0.7)',
  whiteAlpha75: 'rgba(255,255,255,0.75)',
};

export const Colors = {
  light: {
    text: Palette.textDark,
    background: Palette.bg,
    tint: Palette.coral,
    icon: Palette.textMid,
    tabIconDefault: Palette.textSoft,
    tabIconSelected: Palette.coral,
    card: Palette.card,
    border: Palette.border,
    accent: Palette.coral,
    accentAlt: Palette.teal,
    success: Palette.green,
    warning: Palette.yellow,
    danger: Palette.danger,
  },
  dark: {
    text: Palette.textDark,
    background: Palette.bg,
    tint: Palette.coral,
    icon: Palette.textMid,
    tabIconDefault: Palette.textSoft,
    tabIconSelected: Palette.coral,
    card: Palette.card,
    border: Palette.border,
    accent: Palette.coral,
    accentAlt: Palette.teal,
    success: Palette.green,
    warning: Palette.yellow,
    danger: Palette.danger,
  },
};
