# Generated by Django 5.2 on 2026-04-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stellar_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
