# Generated by Django 5.2 on 2026-02-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0002_expopushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
