# Generated by Django 5.2 on 2026-03-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0003_alter_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='government_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='coinapp.exchange'),
        ),
        migrations.DeleteModel(
            name='UserVerification',
        ),
    ]
